package com.berangkat.kerja

val goodNameList = listOf(
        "ancol",
        "angke",
        "bojong gede",
        "bekasi",
        "bekasi timur",
        "bojong indah",
        "bogor",
        "batu ceper",
        "buaran",
        "cibinong",
        "cicayur",
        "cibitung",
        "cilejit",
        "cikini",
        "cikarang",
        "cikoya",
        "cilebut",
        "cisauk",
        "citayam",
        "citeras",
        "cakung",
        "cawang",
        "daru",
        "depok",
        "depok baru",
        "duren kalibata",
        "duri",
        "gondang dia",
        "grogol",
        "gang sentiong",
        "jakarta kota",
        "jayakarta",
        "jurang mangu",
        "jatinegara",
        "juanda",
        "karet",
        "kebayoran",
        "kalideres",
        "klender",
        "klender baru",
        "kemayoran",
        "kramat",
        "kampung bandan",
        "kranji",
        "lenteng agung",
        "mangga besar",
        "maja",
        "manggarai",
        "metland telaga murni",
        "nambo",
        "pondo kranji",
        "poris",
        "palmerah",
        "pondok cina",
        "pondok jati",
        "parung panjang",
        "pasar senen",
        "pesing",
        "pasar minggu",
        "pasar minggu baru",
        "rajawali",
        "rangkas bitung",
        "rawa buntu",
        "rawa buaya",
        "sudimara",
        "serpong",
        "sudirman",
        "sawah besar",
        "tambun",
        "tebet",
        "tenjo",
        "tiga raksa",
        "tanah abang",
        "taman kota",
        "tangerang",
        "tanjung barat",
        "tanjung priuk",
        "tanah tinggi",
        "universitas indonesia",
        "universitas pancasila"
)